/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package CapaPresentacion;

import javax.swing.*;
import javax.swing.event.AncestorEvent;
import java.io.IOException;
import java.util.ArrayList;

/**
 *
 * @author Mingjian
 */
public class VistaAsignarTemas extends javax.swing.JPanel
{

    private ControladorPresentacion controlPre;
    private String tema = null;
    private AncestorEvent evt;

    /**
     * Creates new form VistaAsignarTemas
     */
    public VistaAsignarTemas()
    {
        initComponents();
    }

    // lista de libros de la biblioteca, vista izquierda
    public void updateListBooks()
    {
        ArrayList<String[]> list = controlPre.getAllLibros();
        String[] libro = new String[list.size()];
        int i = 0;
        for (String[] s : list)
        {
            libro[i] = s[2];
            ++i;
        }
        listLibros.setListData(libro);
    }

    // dado un id de libro, carga los temas asignados de este libro, vista derecha
    public void loadTemasAsignados(String Id) throws IOException
    {
        int id = Integer.parseInt(Id);
        ArrayList<String> list = new ArrayList<String>();
        list = controlPre.getTemas(id);
        String temas[] = list.toArray(new String[list.size()]);
        listTemas.setListData(temas);
    }

    public void loadBook(String idL, String nombreT) throws IOException
    {
        controlPre.asignarTemaLibro(idL, nombreT);
        loadTemasAsignados(idL);
    }




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents()
    {

        buttonSave = new javax.swing.JButton();
        buttonAccept = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();
        comboBoxThemes = new javax.swing.JComboBox();
        jScrollPaneLibros = new javax.swing.JScrollPane();
        listLibros = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        buttonAsign = new javax.swing.JButton();
        jScrollPaneTemas = new javax.swing.JScrollPane();
        listTemas = new javax.swing.JList();

        buttonSave.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buttonSave.setText("Guardar Biblioteca");

        buttonAccept.setText("Aceptar");
        buttonAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAcceptActionPerformed(evt);
            }
        });

        buttonCancel.setText("Cancelar");
        buttonAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });

        comboBoxThemes.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                selectThemeAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        listLibros.addAncestorListener(new javax.swing.event.AncestorListener()
        {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt)
            {}
            public void ancestorAdded(javax.swing.event.AncestorEvent evt)
            {
                try {
                    listLibrosAncestorAdded(evt);
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt)
            {}

        });
        jScrollPaneLibros.setViewportView(listLibros);

        listTemas.addAncestorListener(new javax.swing.event.AncestorListener()
        {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt)
            {}
            public void ancestorAdded(javax.swing.event.AncestorEvent evt)
            {
                listTemasAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt)
            {}

        });
        jScrollPaneTemas.setViewportView(listTemas);


        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("temas asignados:");


        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Asignar temas:");

        buttonAsign.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buttonAsign.setText("Asignar");
        buttonAsign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    buttonAsignActionPerformed(evt);
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        });



        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(35, 35, 35)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(buttonAsign, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(comboBoxThemes, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(34, 34, 34)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jScrollPaneTemas))))
                                .addGap(132, 132, 132)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPaneLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1)
                                        .addComponent(buttonSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(buttonAccept, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(buttonCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPaneLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPaneTemas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(7, 7, 7)
                                                .addComponent(comboBoxThemes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(buttonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(buttonAccept, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(buttonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap())
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(buttonAsign)
                                                .addGap(27, 27, 27))))
        );
    }// </editor-fold>                        

    //private methods
    private void listLibrosAncestorAdded (javax.swing.event.AncestorEvent evt) throws IOException
    {
        this.updateListBooks();
        String id = listLibros.getSelectedValue().toString();
        this.loadTemasAsignados(id);
    }

    private void buttonAsignActionPerformed (java.awt.event.ActionEvent evt) throws IOException
    {
        String idLibro = listLibros.getSelectedValue().toString();
        String nombreTema = comboBoxThemes.getSelectedItem().toString();

        if(! controlPre.temaRepetido(idLibro, nombreTema))
            this.loadBook(idLibro, nombreTema);
        else
        {
            JOptionPane.showMessageDialog(this, "ERROR: El tema ya esta asignado :( ", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

    }

    private void selectThemeAncestorAdded (javax.swing.event.AncestorEvent evt)
    {
        ArrayList<String> temas = controlPre.getAllThemes();
        comboBoxThemes.removeAllItems();
        for (String s : temas)
        {
            comboBoxThemes.addItem(s);
        }
        if (tema != null) {
            comboBoxThemes.setSelectedItem(tema);
        }
    }

    private void listTemasAncestorAdded (javax.swing.event.AncestorEvent evt)
    {
        //String nombreLibro = listLibros.getSelectedValue().toString();

    }

    private void buttonAcceptActionPerformed (java.awt.event.ActionEvent evt)
    {

    }

    private void buttonCancelActionPerformed (java.awt.event.ActionEvent evt)
    {
        //controlPre.activeView("CreateLibrary");
    }


    // Variables declaration - do not modify
    private javax.swing.JButton buttonSave;
    private javax.swing.JButton buttonAccept;
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonAsign;
    private javax.swing.JComboBox comboBoxThemes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList listLibros;
    private javax.swing.JList listTemas;
    private javax.swing.JScrollPane jScrollPaneLibros;
    private javax.swing.JScrollPane jScrollPaneTemas;
    // End of variables declaration                   
}
