package CapaPresentacion;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.*;
import java.io.IOException;
import java.util.ArrayList;

/**
 *
 * @author Mingjian
 */
public class VistaTema extends javax.swing.JPanel
{

    private ControladorPresentacion controlPre;
    private VistaClasificacion vistaClasifi;
    private String value;
    private String key;
    private boolean mode;


    /**
     * Creates new form VistaTema
     */
    public VistaTema() {
        initComponents();
    }

    public void setController(ControladorPresentacion controlPre)
    {
        this.controlPre = controlPre;
    }

    public void setMode(boolean item)
    {
        mode = item;
        if(item)
        {
            buttonAC.setText("Crear");
        }
        else
        {
            buttonAC.setText("Modificar");

        }
    }

    public void loadTema(String nombre) throws IOException
    {
        this.key = nombre;
        String nombreTemaP;
        nombreTemaP = controlPre.getPadre(nombre);
        editNombreTema.setText(nombre);
        value = nombreTemaP;
        jComboBox1.setSelectedItem(nombreTemaP);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents()
    {

        buttonAC = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        editNombreTema = new javax.swing.JTextField();


        buttonAC.setText("Crear");
        buttonAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    buttonACActionPerformed(evt);
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        });

        buttonCancel.setText("Cancelar");
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Tema");

        jLabel2.setText("nombre:");

        jLabel3.setText("tema padre:");

        jComboBox1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }

            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                temaPadreAncestorAdded(evt);
            }

            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });


        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(buttonAC)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                                .addComponent(buttonCancel)
                                .addGap(96, 96, 96))
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(70, 70, 70)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel3)
                                                        .addComponent(jLabel2))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(editNombreTema, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(31, 31, 31)
                                                .addComponent(jLabel1)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jLabel1)
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(editNombreTema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(buttonAC)
                                        .addComponent(buttonCancel))
                                .addGap(96, 96, 96))
        );
    }// </editor-fold>

    private void buttonACActionPerformed(java.awt.event.ActionEvent evt) throws IOException
    {
        // mode create
        if(mode)
        {
            if(editNombreTema.getText().equals(""))
            {
                JOptionPane.showMessageDialog(this, "ERROR: Te faltan datos ): ", "Error", JOptionPane.WARNING_MESSAGE);
                return;
            }
            else if(! controlPre.esTemaValido(editNombreTema.getText()))
            {
                JOptionPane.showMessageDialog(this, "ERROR: Tema ya existe ): ", "Error", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }
        // mode modify
        else
        {

            String nombre_nuevo = editNombreTema.getText();
            if(nombre_nuevo.equals(""))
            {
                JOptionPane.showMessageDialog(this, "ERROR: Te faltan datos ): ", "Error", JOptionPane.WARNING_MESSAGE);
                return;
            }
            controlPre.modificarTema(key, nombre_nuevo);
        }
    }

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt)
    {
        editNombreTema.setText("");
        controlPre.activeView("left", "crearClasificacion");
    }

    private void temaPadreAncestorAdded(javax.swing.event.AncestorEvent evt)
    {
        ArrayList<String> temas = controlPre.getAllThemes();
        jComboBox1.removeAllItems();
        for (String s : temas)
        {
            jComboBox1.addItem(s);
        }
        if (value != null) jComboBox1.setSelectedItem(value);
    }//GEN-LAST:event_editTipusAncestorAdded

    // Variables declaration - do not modify
    private javax.swing.JButton buttonAC;
    private javax.swing.JButton buttonCancel;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField editNombreTema;
    // End of variables declaration
}
