package CapaPresentacion;

import java.awt.CardLayout;
import javax.swing.JOptionPane;


/**
 * Created by Mingjian on 02/06/2014.
 */
public class VistaPrincipal extends javax.swing.JFrame
{
    private ControladorPresentacion controlPre;
    //private Component frame;

    public VistaPrincipal(ControladorPresentacion controlPre)
    {
        initComponents();
        this.controlPre = controlPre;
        this.setVisible(true);
        vistaClasifi.setController(controlPre);
        vistaTema.setController(controlPre);
        vistaBiblio.setController(controlPre);
        vistaCollectLibros.setController(controlPre);
        vistaLibro.setController(controlPre);
        vistaAssignTema.setController(controlPre);

        
        // Left view
        CardLayout c = (CardLayout) leftView.getLayout();
        c.show(leftView, "vistaClasificacion");
        c = (CardLayout) rightView.getLayout();

    }

   

    public void activeView(String direction, String item)
    {
        CardLayout card;
        if (direction.equals("left"))
        {
            card = (CardLayout) leftView.getLayout();
            card.show(leftView, item);
        }
        else
        {
            card = (CardLayout) rightView.getLayout();
            card.show(rightView, item);
            activeView("left", "collectLibros");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents()
    {

        vistaClasifi = new VistaClasificacion();
        vistaTema = new VistaTema();
        vistaBiblio = new VistaCrearBiblioteca();
        vistaCollectLibros = new VistaColeccionLibros();
        vistaLibro = new VistaLibro();
        vistaAssignTema = new VistaAsignarTemas();
        leftView = new javax.swing.JPanel();
        rightView = new javax.swing.JPanel();
        buttonExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Proyecto PROP");
        setMinimumSize(new java.awt.Dimension(947, 492));
        setResizable(false);

        leftView.setBackground(new java.awt.Color(196, 255, 243));
        leftView.setLayout(new java.awt.CardLayout());
        leftView.add(vistaClasifi, "vistaClasificacion");
        leftView.add(vistaBiblio, "crearBiblioteca");
        leftView.add(vistaCollectLibros, "collectLibros");
        leftView.add(vistaTema, "crearTema");
        leftView.add(vistaAssignTema, "asignarTemaLibro");

        rightView.setMinimumSize(new java.awt.Dimension(220, 424));
        rightView.setPreferredSize(new java.awt.Dimension(187, 424));
        rightView.setLayout(new java.awt.CardLayout());
        rightView.add(vistaLibro, "crearLibro");

        buttonExit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buttonExit.setBackground(new java.awt.Color(62, 255, 233));
        buttonExit.setText("Exit");
        buttonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(buttonExit)
                                .addContainerGap(516, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(265, Short.MAX_VALUE)
                                .addComponent(buttonExit)
                                .addContainerGap())
        );

        pack();
        // </editor-fold>//GEN-END:initComponents
    }

    private void exitActionPerformed(java.awt.event.ActionEvent evt)
    {
        JOptionPane.showMessageDialog(this, "Adios, Good bye!", "", JOptionPane.INFORMATION_MESSAGE);
        System.exit(0); // para salir del programa...
    }

    
    // Variables declaration - do not modify
    private javax.swing.JButton buttonExit;
    private javax.swing.JPanel leftView;
    private javax.swing.JPanel rightView;
    private VistaLibro vistaLibro;
    private VistaCrearBiblioteca vistaBiblio;
    private VistaTema vistaTema;
    private VistaClasificacion vistaClasifi;
    private VistaColeccionLibros vistaCollectLibros;
    private VistaAsignarTemas vistaAssignTema;
    // End of variables declaration

}
