package CapaPresentacion;

import java.awt.CardLayout;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.awt.Container;


/**
 * Created by Mingjian on 02/06/2014.
 */
public class VistaPrincipal
{
    private ControladorPresentacion controlPre;
    
    protected CardLayout layout;
    
    //private Component frame;

    public VistaPrincipal(ControladorPresentacion controlPre)
    {
        initComponents();
        this.controlPre = controlPre;
        vistaClasifi.setController(controlPre);
        vistaClasifi.setVista(vistaTema);
        vistaTema.setController(controlPre);
        vistaTema.setVista(vistaClasifi);
        vistaBiblio.setController(controlPre);
        vistaCollectLibros.setController(controlPre);
        vistaLibro.setController(controlPre);
        vistaAssignTema.setController(controlPre);
        
        
        layout.show(frameVista.getContentPane(), "vistaClasificacion");
        
        // Left view
        /*CardLayout c = (CardLayout) leftView.getLayout();
        c.show(leftView, "vistaClasificacion");
        c = (CardLayout) rightView.getLayout();*/

    }
    
    public void hacerVisible()
    {
        frameVista.setVisible(true);
        frameVista.pack();
    }
    
    public void activar() {
    frameVista.setEnabled(true);
  }

  public void desactivar() {
    frameVista.setEnabled(false);
  }

   

    public void activeView(String panel)
    {
        if(panel.equal("crearTema"))
        layout.show(frameVista.getContentPane(), panel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents()
    {

        vistaClasifi = new VistaClasificacion();
        vistaTema = new VistaTema();
        vistaBiblio = new VistaCrearBiblioteca();
        vistaCollectLibros = new VistaColeccionLibros();
        vistaLibro = new VistaLibro();
        vistaAssignTema = new VistaAsignarTemas();
        //leftView = new javax.swing.JPanel();
        //rightView = new javax.swing.JPanel();
        
        frameVista.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        frameVista.setTitle("Proyecto PROP");
        frameVista.setMinimumSize(new java.awt.Dimension(200, 200));
        frameVista.setResizable(true);
        
        Container pane = frameVista.getContentPane();
        Container paneFinal = frameVista.getContentPane();
        layout = new CardLayout();
        
        pane.setLayout(layout);
        paneFinal.setLayout(layout);
        pane.add(vistaClasifi, "vistaClasificacion");
        paneFinal.add(vistaTema, "crearTema");
        
        //JPanel contentPane = (JPanel) frameVista.getContentPane();
        //contentPane.add(vistaClasifi);

        /*leftView.setBackground(new java.awt.Color(196, 255, 243));
        leftView.setLayout(new java.awt.CardLayout());
        leftView.add(vistaClasifi, "vistaClasificacion");
        leftView.add(vistaBiblio, "crearBiblioteca");
        leftView.add(vistaCollectLibros, "collectLibros");
        leftView.add(vistaTema, "crearTema");
        leftView.add(vistaAssignTema, "asignarTemaLibro");

        rightView.setMinimumSize(new java.awt.Dimension(220, 424));
        rightView.setPreferredSize(new java.awt.Dimension(187, 424));
        rightView.setLayout(new java.awt.CardLayout());
        rightView.add(vistaLibro, "crearLibro");*/

    }

    
    // Variables declaration - do not modify
    private JFrame frameVista = new JFrame("Vista Principal");
    //private javax.swing.JPanel leftView;
    //private javax.swing.JPanel rightView;
    private VistaLibro vistaLibro;
    private VistaCrearBiblioteca vistaBiblio;
    private VistaTema vistaTema;
    private VistaClasificacion vistaClasifi;
    private VistaColeccionLibros vistaCollectLibros;
    private VistaAsignarTemas vistaAssignTema;
    // End of variables declaration

}
