package CapaPresentacion;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.*;
import java.io.IOException;
import java.util.ArrayList;

/**
 *
 * @author Mingjian
 */
public class VistaClasificacion extends javax.swing.JPanel
{

    private ControladorPresentacion controlPre;
    private VistaTema vistaTema;

    /**
     * Creates new form VistaClasificacion
     */
    public VistaClasificacion()
    {
        
        initComponents();
    }

    public void setController(ControladorPresentacion controlPre)
    {
        this.controlPre = controlPre;
    }

    public void rebootLabelandList()
    {
        editNombre.setText("");
        listTemas.removeAll();
    }

    public void updateListThemes()
    {
        ArrayList<String> list = controlPre.getAllThemes();
        String[] temas = new String [list.size()];
        int i = 0;
        for(String s : list)
        {
            temas[i] = s;
            ++i;
        }
        listTemas.setListData(temas);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents()
    {

        buttonSave = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        editNombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        listTemas = new javax.swing.JList();
        buttonCreate = new javax.swing.JButton();
        buttonModify = new javax.swing.JButton();
        buttonDelete = new javax.swing.JButton();

        buttonSave.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        buttonSave.setText("Guardar");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Clasificacion");

        jLabel2.setText("Nombre:");

        editNombre.addActionListener((java.awt.event.ActionEvent evt) -> {
            editNombreActionPerformed(evt);
        });
        
        buttonSave.addActionListener((java.awt.event.ActionEvent evt) -> {
            saveClasificacionActionPerformed(evt);
        });

        listTemas.addAncestorListener(new javax.swing.event.AncestorListener() {
            @Override
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            @Override
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                listTemasAncestorAdded(evt);
            }
            @Override
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(listTemas);

        buttonCreate.setText("Crear ");
        buttonCreate.addActionListener((java.awt.event.ActionEvent evt) -> {
            buttonCreateActionPerformed(evt);
        });

        buttonModify.setText("Modificar");
        buttonModify.addActionListener((java.awt.event.ActionEvent evt) -> {
            try {
                buttonModifyActionPerformed(evt);
            } catch (IOException e) {
            }
        });

        buttonDelete.setText("Eliminar");
        buttonDelete.addActionListener((java.awt.event.ActionEvent evt) -> {
            try {
                buttonDeleteActionPerformed(evt);
            } catch (IOException e) {
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(buttonCreate))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonModify)
                        .addGap(18, 18, 18)
                        .addComponent(buttonDelete)
                        .addGap(27, 27, 27)
                        .addComponent(buttonSave))
                    .addComponent(editNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(86, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(editNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonModify)
                            .addComponent(buttonCreate)
                            .addComponent(buttonDelete))
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(buttonSave)
                        .addGap(23, 23, 23))))
        );
    }// </editor-fold>          

    private void editNombreActionPerformed(java.awt.event.ActionEvent evt)
    {
        editNombre.setText("");
    }
    
    private void saveClasificacionActionPerformed(java.awt.event.ActionEvent evt)
    {
        if(editNombre.getText().equals("") || (controlPre.esEmptyClasifi()))
        {
            JOptionPane.showMessageDialog(this, "ERROR: Te faltan datos ): ", "Error", JOptionPane.WARNING_MESSAGE);
        }
        else
        {
            //controlPre.activeView("left", "crearBiblioteca");
            rebootLabelandList();
        }
    }

    private void buttonCreateActionPerformed(java.awt.event.ActionEvent evt)
    {
        if(! controlPre.esEmptyClasifi())
        {
            vistaTema.setMode(true);
            //controlPre.activeView("left", "crearTema");
        }
        else
            buttonCreate.setEnabled(false);
    }

    private void buttonModifyActionPerformed(java.awt.event.ActionEvent evt)  throws IOException
    {
        if(! controlPre.esEmptyClasifi())
        {
            String nombreTema = listTemas.getSelectedValue().toString();
            if(nombreTema.equals("General"))
            {
                JOptionPane.showMessageDialog(this, "ERROR: No se puede modificar tema General ", "Error", JOptionPane.WARNING_MESSAGE);
                return;
            }
            vistaTema.loadTema(nombreTema);
            vistaTema.setMode(false);
            //controlPre.activeView("left", "crearTema");
        }
        else
            buttonModify.setEnabled(false);
    }

    private void buttonDeleteActionPerformed(java.awt.event.ActionEvent evt) throws IOException
    {
        String nombreTema = listTemas.getSelectedValue().toString();
        controlPre.eliminarTema(nombreTema);
        this.updateListThemes();
    }

    private void listTemasAncestorAdded(javax.swing.event.AncestorEvent evt)
    {
        this.updateListThemes();
    }

    // Variables declaration - do not modify
    private javax.swing.JButton buttonSave;
    private javax.swing.JButton buttonCreate;
    private javax.swing.JButton buttonModify;
    private javax.swing.JButton buttonDelete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList listTemas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField editNombre;
    // End of variables declaration
}
